# NumPy

## Accessing Array Elements

Often, we want to access the data contained inside an array, for the purpose of either modifying the data or using it in later computation. For 1d arrays, the simplest way to do this is very similar to how we would do so for a list: 

In [2]:
import numpy as np
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
# zero indexing
print(a[0])

1


In [4]:
print(a[-1])

10


In [5]:
# slicing
print(a[:4])

[1 2 3 4]


In [6]:
# 'fancy' indexing
# passing a list lets you single out individual values
print(a[3], a[7], a[9])
print(a[[3,7,9]], type(a[[3,7,9]]))
print(a[[3,9,7]], type(a[[3,9,7]]))

4 8 10
[ 4  8 10] <class 'numpy.ndarray'>
[ 4 10  8] <class 'numpy.ndarray'>


An extremely useful technique is boolean indexing. The important points about boolean indexing is that boolean comparisons in `numpy` are vectorized, and generate arrays of boolean values. 

In [7]:
# boolean indexing
# passing an array of True/False lets you grab elements according to a criterion
print(a>5)
print(a[a>5])

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]


We can also compare two arrays of the same size: 

In [8]:
b = np.random.randint(0,10,10)
print(type(b),b)

<class 'numpy.ndarray'> [8 7 0 5 2 0 7 8 6 5]


In [10]:
# compare two arrays of same size
print(b>a)
print(a[b>a],b[b>a])

[ True  True False  True False False  True False False False]
[1 2 4 7] [2 8 6 8]


We can then pass these boolean arrays to select only the elements of an array for which the boolean array has value True.

In [11]:
indices = a  >5
print(a[indices])

[ 6  7  8  9 10]


In [11]:
print(a[a>9])           # gives the element NOT the position 

[10]


Usually, we would write this a bit more compactly: 

In [12]:
a[a>5]

array([ 6,  7,  8,  9, 10])

We can also use the bitwise & and | operators to comibine multiple conditions:

In [12]:
print(a[(a>5) | (a%2 == 0)])

[ 2  4  6  7  8  9 10]


## Modifying Array Entries

After having accessed array entries, it's easy to modify them: 

In [13]:
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# **You can modify numpy array elements same as lists !**

In [14]:
# modifying a single value
a[3] = 5
a

array([ 0,  1,  2,  5,  4,  5,  6,  7,  8,  9, 10])

In [17]:
# setting multiple values using a single number
a[a>5] = 5
print(a)

b = np.arange(1,11)
b[b>8] = 100
print(b)

[0 1 2 5 4 5 5 5 5 5 5]
[  1   2   3   4   5   6   7   8 100 100]


In [18]:
# using an array to set multiple values
a[a==5] = np.array([2,3,4,5,6,7,8])
a

array([0, 1, 2, 2, 4, 3, 4, 5, 6, 7, 8])

In [19]:
# will lead to errors if the sizes don't match

## Indexing Multidimensional Arrays

What about when we're dealing with multidimensional arrays? 

In [21]:
A = np.reshape(np.arange(15),(3,5))         # initially one row, 15 col then reshape to 3 row, 15 col 
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In this case, we use commas to separate indices along different dimensions. In the case of 2d arrays, it's often convenient to think about the first dimension as representing "rows" and the second as representing "columns." 

In [24]:
# zeroth row, second column
print(A[0,2])

# second row, first col
print(A[2,0])

2
10


In [26]:
# last row, zeroth column
print(A[-1,0])

10


We can also extract entire rows or columns at a time. The `:` here means "everything along the dimension". 

In [27]:
B = np.arange(1,10)
C = B.reshape(3,3)

print(C[:,:])
print(C[:,0])
print(C[0,:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 4 7]
[1 2 3]


In [28]:
# entire zeroth row
A[0,:]

array([0, 1, 2, 3, 4])

In [29]:
# zeroth column
A[:,0]

array([ 0,  5, 10])

In [30]:
# same as A
A[:,:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [31]:
# all the odd numbers
print(A[A%2 == 1])

[ 1  3  5  7  9 11 13]


In [32]:
# add 2 to all the odd numbers
A[A%2 == 1] +=2
A

array([[ 0,  3,  2,  5,  4],
       [ 7,  6,  9,  8, 11],
       [10, 13, 12, 15, 14]])

Indexing gets more complex in higher dimensions, but we generally won't work with higher-dimensional arrays in this course. 

## Functions of Arrays

In [33]:
a = np.arange(1,11)
b = np.arange(11,21)
print(a,b)

[ 1  2  3  4  5  6  7  8  9 10] [11 12 13 14 15 16 17 18 19 20]


# **I am guessing the caveat is that for these operations ivolving two arrays they gotta be of the same size**

In [34]:
# negate an array
print(-a)

[ -1  -2  -3  -4  -5  -6  -7  -8  -9 -10]


In [35]:
# absolute value
np.abs(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
# entrywise addition
a+b

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [ ]:
print(a-b)
print(a+b)
print(a **b)                        

[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
[12 14 16 18 20 22 24 26 28 30]
[                  1                4096             1594323
           268435456         30517578125       2821109907456
     232630513987207   18014398509481984 1350851717672992089
 7766279631452241920]


In [38]:
theta = np.linspace(0,np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [39]:
print(np.sin(theta),np.cos(theta),np.tan(theta))

[0.0000000e+00 1.0000000e+00 1.2246468e-16] [ 1.000000e+00  6.123234e-17 -1.000000e+00] [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [40]:
x = np.array([1,2,3])

In [41]:
# natural log (ln)
print(np.exp(x),np.log(x),np.log2(x),np.log10(x))

[ 2.71828183  7.3890561  20.08553692] [0.         0.69314718 1.09861229] [0.        1.        1.5849625] [0.         0.30103    0.47712125]


In [42]:
x = np.array([-1,2])
y = np.log(x)
print(y)

[       nan 0.69314718]


/var/folders/r6/n0wh2lcs2dl98_73bdgpck3h0000gn/T/ipykernel_45715/895219804.py:2: RuntimeWarning: invalid value encountered in log
  y = np.log(x)


In [43]:
print(y+2)

[       nan 2.69314718]


In [44]:
z = np.array([1,2])
r = np.zeros(2)
print(z/r)

[inf inf]


/var/folders/r6/n0wh2lcs2dl98_73bdgpck3h0000gn/T/ipykernel_45715/2092111873.py:3: RuntimeWarning: divide by zero encountered in divide
  print(z/r)


In [45]:
print(r/r)

[nan nan]


/var/folders/r6/n0wh2lcs2dl98_73bdgpck3h0000gn/T/ipykernel_45715/519070884.py:1: RuntimeWarning: invalid value encountered in divide
  print(r/r)


## Aggregation Functions

In [46]:
a = np.arange(10)
a 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.sum(a)

np.int64(45)

In [48]:
# equivalent to:
a.sum()

np.int64(45)

In [49]:
a.mean()

np.float64(4.5)

In [50]:
print(a.min(), a.max())

0 9


In [51]:
# for product 
print(a.prod())

0


In [52]:
# example: a.shape gives me (3, 5), np.prod(a.shape) gives me 15, which is the number of elements in the array
print(np.prod(a.shape))

10


In [53]:
a.shape

(10,)

In [54]:
A.sum()

np.int64(119)